# Site settings
title: Rannie’s Page
email: cocoarannie@163.com
description: 关于iOS开发的Blog以及点点滴滴。
logo: site_logo.png
url: http://rannie.github.io
weibo_username: cocoarannie
github_username:  rannie

# Build settings
markdown: kramdown
